//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.LectureExample
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Order.
    /// </summary>
    // *** Start programmer edit section *** (Order CustomAttributes)

    // *** End programmer edit section *** (Order CustomAttributes)
    [AutoAltered()]
    [Caption("Заказ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("OrderE", new string[] {
            "Status as \'Status\'",
            "ShipmentDate as \'Shipment date\'",
            "PaymentDay as \'Payment day\'",
            "TotalSum as \'Total sum\'"})]
    [AssociatedDetailViewAttribute("OrderE", "OrderItem", "OrderItemE", true, "", "Order item", true, new string[] {
            ""})]
    [View("OrderL", new string[] {
            "Status as \'Status\'",
            "ShipmentDate as \'Shipment date\'",
            "PaymentDay as \'Payment day\'",
            "TotalSum as \'Total sum\'"})]
    public class Order : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.LectureExample.OrderStatus fStatus;
        
        private System.DateTime fShipmentDate;
        
        private System.DateTime fPaymentDay;
        
        private IIS.LectureExample.DetailArrayOfOrderItem fOrderItem;
        
        // *** Start programmer edit section *** (Order CustomMembers)

        // *** End programmer edit section *** (Order CustomMembers)

        
        /// <summary>
        /// PaymentDay.
        /// </summary>
        // *** Start programmer edit section *** (Order.PaymentDay CustomAttributes)

        // *** End programmer edit section *** (Order.PaymentDay CustomAttributes)
        public virtual System.DateTime PaymentDay
        {
            get
            {
                // *** Start programmer edit section *** (Order.PaymentDay Get start)

                // *** End programmer edit section *** (Order.PaymentDay Get start)
                System.DateTime result = this.fPaymentDay;
                // *** Start programmer edit section *** (Order.PaymentDay Get end)

                // *** End programmer edit section *** (Order.PaymentDay Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Order.PaymentDay Set start)

                // *** End programmer edit section *** (Order.PaymentDay Set start)
                this.fPaymentDay = value;
                // *** Start programmer edit section *** (Order.PaymentDay Set end)

                // *** End programmer edit section *** (Order.PaymentDay Set end)
            }
        }
        
        /// <summary>
        /// ShipmentDate.
        /// </summary>
        // *** Start programmer edit section *** (Order.ShipmentDate CustomAttributes)

        // *** End programmer edit section *** (Order.ShipmentDate CustomAttributes)
        public virtual System.DateTime ShipmentDate
        {
            get
            {
                // *** Start programmer edit section *** (Order.ShipmentDate Get start)

                // *** End programmer edit section *** (Order.ShipmentDate Get start)
                System.DateTime result = this.fShipmentDate;
                // *** Start programmer edit section *** (Order.ShipmentDate Get end)

                // *** End programmer edit section *** (Order.ShipmentDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Order.ShipmentDate Set start)

                // *** End programmer edit section *** (Order.ShipmentDate Set start)
                this.fShipmentDate = value;
                // *** Start programmer edit section *** (Order.ShipmentDate Set end)

                // *** End programmer edit section *** (Order.ShipmentDate Set end)
            }
        }
        
        /// <summary>
        /// Status.
        /// </summary>
        // *** Start programmer edit section *** (Order.Status CustomAttributes)

        // *** End programmer edit section *** (Order.Status CustomAttributes)
        public virtual IIS.LectureExample.OrderStatus Status
        {
            get
            {
                // *** Start programmer edit section *** (Order.Status Get start)

                // *** End programmer edit section *** (Order.Status Get start)
                IIS.LectureExample.OrderStatus result = this.fStatus;
                // *** Start programmer edit section *** (Order.Status Get end)

                // *** End programmer edit section *** (Order.Status Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Order.Status Set start)

                // *** End programmer edit section *** (Order.Status Set start)
                this.fStatus = value;
                // *** Start programmer edit section *** (Order.Status Set end)

                // *** End programmer edit section *** (Order.Status Set end)
            }
        }
        
        /// <summary>
        /// TotalSum.
        /// </summary>
        // *** Start programmer edit section *** (Order.TotalSum CustomAttributes)

        // *** End programmer edit section *** (Order.TotalSum CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual double TotalSum
        {
            get
            {
                // *** Start programmer edit section *** (Order.TotalSum Get)
                return 0;
                // *** End programmer edit section *** (Order.TotalSum Get)
            }
            set
            {
                // *** Start programmer edit section *** (Order.TotalSum Set)

                // *** End programmer edit section *** (Order.TotalSum Set)
            }
        }
        
        /// <summary>
        /// Order.
        /// </summary>
        // *** Start programmer edit section *** (Order.OrderItem CustomAttributes)

        // *** End programmer edit section *** (Order.OrderItem CustomAttributes)
        public virtual IIS.LectureExample.DetailArrayOfOrderItem OrderItem
        {
            get
            {
                // *** Start programmer edit section *** (Order.OrderItem Get start)

                // *** End programmer edit section *** (Order.OrderItem Get start)
                if ((this.fOrderItem == null))
                {
                    this.fOrderItem = new IIS.LectureExample.DetailArrayOfOrderItem(this);
                }
                IIS.LectureExample.DetailArrayOfOrderItem result = this.fOrderItem;
                // *** Start programmer edit section *** (Order.OrderItem Get end)

                // *** End programmer edit section *** (Order.OrderItem Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Order.OrderItem Set start)

                // *** End programmer edit section *** (Order.OrderItem Set start)
                this.fOrderItem = value;
                // *** Start programmer edit section *** (Order.OrderItem Set end)

                // *** End programmer edit section *** (Order.OrderItem Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "OrderE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OrderE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OrderE", typeof(IIS.LectureExample.Order));
                }
            }
            
            /// <summary>
            /// "OrderL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OrderL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OrderL", typeof(IIS.LectureExample.Order));
                }
            }
        }
    }
}
