//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.LectureExample
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Order status.
    /// </summary>
    // *** Start programmer edit section *** (OrderStatus CustomAttributes)

    // *** End programmer edit section *** (OrderStatus CustomAttributes)
    public enum OrderStatus
    {
        
        // *** Start programmer edit section *** (OrderStatus.Новый CustomAttributes)

        // *** End programmer edit section *** (OrderStatus.Новый CustomAttributes)
        Новый,
        
        // *** Start programmer edit section *** (OrderStatus.Оплаченный CustomAttributes)

        // *** End programmer edit section *** (OrderStatus.Оплаченный CustomAttributes)
        Оплаченный,
        
        // *** Start programmer edit section *** (OrderStatus.Отменённый CustomAttributes)

        // *** End programmer edit section *** (OrderStatus.Отменённый CustomAttributes)
        Отменённый,
    }
}
